name: Workshift System CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.1
      - name: Set up JDK 8
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '8.0.432'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.1.0
      - name: Execute Gradle 'check' task
        run: ./gradlew check
      - name: Build the Docker image
        run: docker image build . --platform linux/amd64
