name: Workshift System CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.0
      - name: Set up JDK 8
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '8.0.422'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.5.0
      - name: Execute Gradle 'test' task
        run: ./gradlew test