name: Workshift System CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 8
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '8.0.432'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.1.0
      - name: Execute Gradle 'check' task
        run: ./gradlew check --continue --no-daemon --no-watch-fs
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v3.7.1
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
